version: '3'
services: 
  # postgres:
  #   image: 'postgres:latest'
  redis:
    image: "bitnami/redis:latest"
    command: redis-server --requirepass hubbie_pass
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/usr/local/etc/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment: 
  #     - IS_DOCKERIZED=true # default
  #   ports:
  #     - "4000:4000"
  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  # worker:
  #   environment: 
  #     - IS_DOCKERIZED=true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes: 
  #     - /app/node_modules
  #     - ./worker:/app
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
